/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#18181b",
        "on-tertiary-container": "#bbf7d0",
        "surface-bright": "#18181b",
        "on-tertiary-fixed-variant": "#047857",
        "on-primary-container": "#ede9fe",
        "on-background": "#fafafa",
        "on-tertiary": "#001a12",
        "on-primary-fixed": "#2e1065",
        tertiary: "#34d399",
        "inverse-primary": "#5b21b6",
        "outline-variant": "#27272a",
        "on-secondary": "#09090b",
        "surface-variant": "#18181b",
        "tertiary-fixed-dim": "#6ee7b7",
        "on-error": "#1a0000",
        "tertiary-fixed": "#bbf7d0",
        "surface-tint": "#a78bfa",
        "on-secondary-fixed-variant": "#3f3f46",
        "surface-dim": "#0c0c0f",
        primary: "#a78bfa",
        "error-container": "#3b1111",
        "on-secondary-container": "#a1a1aa",
        "primary-fixed-dim": "#c4b5fd",
        "surface-container-low": "#0f0f12",
        surface: "#0c0c0f",
        "tertiary-container": "#065f46",
        "surface-container": "#121215",
        "secondary-container": "#27272a",
        "surface-container-highest": "#1e1e22",
        "on-error-container": "#fca5a5",
        "on-surface-variant": "#a1a1aa",
        "on-tertiary-fixed": "#003318",
        "surface-container-high": "#18181b",
        "primary-container": "#7c3aed",
        error: "#ef4444",
        background: "#09090b",
        "surface-container-lowest": "#09090b",
        secondary: "#71717a",
        "on-primary": "#0a0012",
        "inverse-on-surface": "#09090b",
        "secondary-fixed": "#a1a1aa",
        outline: "#52525b",
        "on-primary-fixed-variant": "#5b21b6",
        "primary-fixed": "#ede9fe",
        "secondary-fixed-dim": "#71717a",
        "on-surface": "#fafafa",
        "inverse-surface": "#fafafa",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Geist"],
        display: ["Geist"],
        body: ["Geist"],
        label: ["Geist"],
      },
    },
  },
};
